version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
  deploy:
    docker:
      - image: circleci/php:7.1-node-browsers
    parameters:
      cloud:
        default: google
        type: string
    steps:
      - checkout
      - run: echo "Deploying << parameters.cloud >>"

workflows:
  commit:
    jobs:
      - build:
          name: build_app
      - deploy:
          name: deploy_google
          cloud: google
          requires:
            - build_app
      - deploy:
          name: deploy_aws
          cloud: aws
          requires:
            - build_app

