version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
  deploy:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: echo "Deploying"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          name: build_app
      - deploy:
          name: deploy_to_google
          requires:
            - build_app
      - deploy:
          name: deploy_to_aws
          requires:
            - build_app

